### ISSUE TITLE
Windows : 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by mogab9** [apiaryio/api-blueprint-sublime-plugin#8]
Hello,

I've tried using this plugin without success on **Windows 7x64** with **Sublime 3**. I've found a working solution but first, here's the traceback:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "C:\Users\Gabriel\AppData\Roaming\Sublime Text 3\Packages\API Blueprint\APIBlueprint.py", line 85, in run
    result = run_command ("snowcrash", args=args, source=source)
  File "C:\Users\Gabriel\AppData\Roaming\Sublime Text 3\Packages\API Blueprint\APIBlueprint.py", line 39, in run_command
    stat = proc.communicate(input=source)
  File "X/subprocess.py", line 906, in communicate
  File "X/subprocess.py", line 1180, in _communicate
TypeError: 'str' does not support the buffer interface
```

This error is very common and related to Python string encoding. 

My **solution** was to completely remove win32 code in **APIBlueprint.py** in **def run_command()** and then it worked: 

```
def run_command(cmd, args = [], source="", cwd = None, env = None):
  settings = sublime.load_settings('APIBlueprint.sublime-settings')

  if not type(args) is list:
    args = [args]
  
  #if sys.platform == "win32":
    #proc = Popen([cmd]+args, env=env, cwd=cwd, stdout=PIPE, stdin=PIPE, stderr=PIPE, shell=True)
    #stat = proc.communicate(input=source)
  
  #else:
  if env is None:
    env = {"PATH": settings.get('binDir', '/usr/local/bin')}

    command = [cmd] + args
    
    proc = Popen(command, env=env, cwd=cwd, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    stat = proc.communicate(input=source.encode('utf-8'))
  
  okay = proc.returncode == 0
  
  #remove leading empty line
  lines = stat[1].decode('UTF-8').split('\n')
  if not lines[0]:
    lines.pop(0)
  sanitized_errout = '\n'.join(lines)

  return {"okay": okay, "out": stat[0].decode('UTF-8'), "err": sanitized_errout}
```

**Comment by danielgtaylor** [comment]
The fix for this was merged on 14 Aug 2014; closing.
